language: ruby
rvm:
- 2.1
sudo: false
before_script:
  - pip install --user yamllint
  - pip install --user yamale
script:
  - yamllint docs/_data/*
  - ruby tests/test_filesRootDirectory.rb
  - ruby tests/test_fileTypeLogin.rb
  - ruby tests/test_infoValidation.rb
  - bundle exec jekyll build
